version: '3.8'

services:
  
  recommendation-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PYTHONPATH=.
      - APP_HOST=0.0.0.0
      - APP_PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
